// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v3/auth/captcha": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录相关"
                ],
                "summary": "获取验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/error.ResponseWithData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RspGenCaptcha"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录相关"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ReqLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/error.ResponseWithData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RspLogin"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ReqAddUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/error.ResponseWithData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RspAddUser"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/user/:id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "编辑用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ReqUpdateUser"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/error.Response"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/error.Response"
                        }
                    }
                }
            }
        },
        "/api/v3/user/:id/password": {
            "put": {
                "description": "超级管理员重置指定用户的密码为默认密码，用户登录时需要重设密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "超管给用户重置初始密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/error.Response"
                        }
                    }
                }
            }
        },
        "/api/v3/user/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改个人密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ReqUpdateMyPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/error.Response"
                        }
                    }
                }
            }
        },
        "/api/v3/user/phone": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改个人手机号",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ReqUpdateMyPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/error.Response"
                        }
                    }
                }
            }
        },
        "/api/v3/users": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "第几页，默认从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页结果数",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：用户名（模糊匹配）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：部门id",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：角色id",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/error.ResponseWithData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RspGetUserList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/users/deleted": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "已删除用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "第几页，默认从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页结果数",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：用户名（模糊匹配）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：部门id",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：角色id",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/error.ResponseWithData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RspGetDeletedUserList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/users/render": {
            "get": {
                "description": "获取简要信息，用于下拉框等场景",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户render列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "第几页，默认从1开始",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页结果数",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：用户名、姓名或警号（模糊匹配）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：部门id",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选条件：角色id",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/error.ResponseWithData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.RspGetUserRender"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "error.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code 错误码",
                    "type": "integer"
                },
                "msg": {
                    "description": "msg 消息",
                    "type": "string"
                }
            }
        },
        "error.ResponseWithData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "code 错误码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据信息",
                    "type": "object"
                },
                "msg": {
                    "description": "msg 消息",
                    "type": "string"
                }
            }
        },
        "handler.ReqAddUser": {
            "type": "object",
            "required": [
                "account",
                "department",
                "name",
                "role"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "department": {
                    "description": "部门id",
                    "type": "string"
                },
                "name": {
                    "description": "用户名",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "police_number": {
                    "description": "警号",
                    "type": "string"
                },
                "role": {
                    "description": "角色id",
                    "type": "string"
                }
            }
        },
        "handler.ReqLogin": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "验证码ID",
                    "type": "string"
                },
                "captcha_result": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "handler.ReqUpdateMyPassword": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "description": "新密码",
                    "type": "string"
                }
            }
        },
        "handler.ReqUpdateUser": {
            "type": "object",
            "required": [
                "set"
            ],
            "properties": {
                "set": {
                    "description": "增量修改",
                    "$ref": "#/definitions/service.SetUser"
                }
            }
        },
        "handler.RspAddUser": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户id",
                    "type": "string"
                }
            }
        },
        "handler.RspDeletedUserData": {
            "type": "object",
            "properties": {
                "_id": {
                    "description": "主键（务必设置omitempty，让驱动自动生成）",
                    "type": "string"
                },
                "account": {
                    "description": "登录账号",
                    "type": "string"
                },
                "department": {
                    "description": "部门名",
                    "type": "string"
                },
                "name": {
                    "description": "显示名",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "police_number": {
                    "description": "警号",
                    "type": "string"
                },
                "role": {
                    "description": "角色名",
                    "type": "string"
                },
                "update_time": {
                    "description": "删除时间-时间戳",
                    "type": "integer"
                },
                "updator": {
                    "description": "删除者姓名",
                    "type": "string"
                }
            }
        },
        "handler.RspGenCaptcha": {
            "type": "object",
            "properties": {
                "captcha_base64": {
                    "description": "验证码图片",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "验证码id",
                    "type": "string"
                }
            }
        },
        "handler.RspGetDeletedUserList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.RspDeletedUserData"
                    }
                },
                "total": {
                    "description": "结果集总数",
                    "type": "integer"
                }
            }
        },
        "handler.RspGetUserList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.RspUserData"
                    }
                },
                "total": {
                    "description": "结果集总数",
                    "type": "integer"
                },
                "total_deleted": {
                    "description": "已删除总数",
                    "type": "integer"
                }
            }
        },
        "handler.RspGetUserRender": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.RspUserRenderData"
                    }
                },
                "total": {
                    "description": "结果集总数",
                    "type": "integer"
                }
            }
        },
        "handler.RspLogin": {
            "type": "object",
            "properties": {
                "need_reset": {
                    "description": "是否需要重设密码",
                    "type": "boolean"
                }
            }
        },
        "handler.RspUserData": {
            "type": "object",
            "properties": {
                "_id": {
                    "description": "主键（务必设置omitempty，让驱动自动生成）",
                    "type": "string"
                },
                "account": {
                    "description": "登录账号",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间-时间戳",
                    "type": "integer"
                },
                "creator": {
                    "description": "创建者姓名",
                    "type": "string"
                },
                "department": {
                    "description": "部门名",
                    "type": "string"
                },
                "name": {
                    "description": "显示名",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "police_number": {
                    "description": "警号",
                    "type": "string"
                },
                "role": {
                    "description": "角色名",
                    "type": "string"
                },
                "update_time": {
                    "description": "修改时间-时间戳",
                    "type": "integer"
                },
                "updator": {
                    "description": "修改者姓名",
                    "type": "string"
                }
            }
        },
        "handler.RspUserRenderData": {
            "type": "object",
            "properties": {
                "_id": {
                    "description": "主键",
                    "type": "string"
                },
                "name": {
                    "description": "显示名",
                    "type": "string"
                }
            }
        },
        "service.SetUser": {
            "type": "object",
            "properties": {
                "department": {
                    "description": "部门id",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "policeNumber": {
                    "description": "警号",
                    "type": "string"
                },
                "role": {
                    "description": "角色id",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Go account API",
	Description: "account服务",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
