// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package account

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountClient interface {
	// 新增操作记录
	AddOperation(ctx context.Context, in *ReqAddOperation, opts ...grpc.CallOption) (*RspAddOperation, error)
	// 数据来源
	GetsPlatform(ctx context.Context, in *ReqGetsPlatform, opts ...grpc.CallOption) (*RspGetsPlatform, error)
}

type accountClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountClient(cc grpc.ClientConnInterface) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) AddOperation(ctx context.Context, in *ReqAddOperation, opts ...grpc.CallOption) (*RspAddOperation, error) {
	out := new(RspAddOperation)
	err := c.cc.Invoke(ctx, "/account.Account/AddOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetsPlatform(ctx context.Context, in *ReqGetsPlatform, opts ...grpc.CallOption) (*RspGetsPlatform, error) {
	out := new(RspGetsPlatform)
	err := c.cc.Invoke(ctx, "/account.Account/GetsPlatform", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
// All implementations must embed UnimplementedAccountServer
// for forward compatibility
type AccountServer interface {
	// 新增操作记录
	AddOperation(context.Context, *ReqAddOperation) (*RspAddOperation, error)
	// 数据来源
	GetsPlatform(context.Context, *ReqGetsPlatform) (*RspGetsPlatform, error)
	mustEmbedUnimplementedAccountServer()
}

// UnimplementedAccountServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (UnimplementedAccountServer) AddOperation(context.Context, *ReqAddOperation) (*RspAddOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOperation not implemented")
}
func (UnimplementedAccountServer) GetsPlatform(context.Context, *ReqGetsPlatform) (*RspGetsPlatform, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetsPlatform not implemented")
}
func (UnimplementedAccountServer) mustEmbedUnimplementedAccountServer() {}

// UnsafeAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServer will
// result in compilation errors.
type UnsafeAccountServer interface {
	mustEmbedUnimplementedAccountServer()
}

func RegisterAccountServer(s grpc.ServiceRegistrar, srv AccountServer) {
	s.RegisterService(&Account_ServiceDesc, srv)
}

func _Account_AddOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAddOperation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).AddOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/AddOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).AddOperation(ctx, req.(*ReqAddOperation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetsPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetsPlatform)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetsPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetsPlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetsPlatform(ctx, req.(*ReqGetsPlatform))
	}
	return interceptor(ctx, in, info, handler)
}

// Account_ServiceDesc is the grpc.ServiceDesc for Account service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Account_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOperation",
			Handler:    _Account_AddOperation_Handler,
		},
		{
			MethodName: "GetsPlatform",
			Handler:    _Account_GetsPlatform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
